# Generated by Django 4.2.26 on 2025-11-13 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ESIMDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iccid", models.CharField(db_index=True, max_length=50, unique=True)),
                ("order_sim_id", models.CharField(blank=True, max_length=100)),
                ("plan_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("INSTALLED", "Installed"),
                            ("RELEASED", "Released"),
                            ("ENABLED", "Enabled"),
                            ("DISABLED", "Disabled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purchase_date", models.CharField(blank=True, max_length=50)),
                ("validity_days", models.IntegerField(blank=True, null=True)),
                (
                    "data_capacity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("data_capacity_unit", models.CharField(default="GB", max_length=10)),
                (
                    "data_consumed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("data_consumed_unit", models.CharField(default="GB", max_length=10)),
                (
                    "data_remaining",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("data_remaining_unit", models.CharField(default="GB", max_length=10)),
                ("activation_code", models.TextField(blank=True)),
                ("apn", models.CharField(blank=True, max_length=255)),
                ("api_provider", models.CharField(max_length=20)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "eSIM Details",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.CreateModel(
            name="ESIMQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iccid", models.CharField(db_index=True, max_length=50)),
                (
                    "api_provider",
                    models.CharField(
                        choices=[
                            ("AIRHUB", "AirHub"),
                            ("ESIMCARD", "eSIMCard"),
                            ("TRAVELROAM", "TravelRoam"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "query_timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("response_time_ms", models.IntegerField(blank=True, null=True)),
                ("was_successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("cached_response", models.JSONField(blank=True, null=True)),
                ("cache_expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-query_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["iccid", "-query_timestamp"],
                        name="pulse_esimq_iccid_7403f8_idx",
                    )
                ],
            },
        ),
    ]
